#!/usr/bin/env python3
"""
Environment Setup Script for Tkinter Chat Application

This script helps users set up Firebase environment variables easily.
Run this script and follow the prompts to configure your Firebase credentials.
"""

import os
import json
import sys

def print_banner():
    print("=" * 60)
    print("🚀 Tkinter Chat Application - Environment Setup")
    print("=" * 60)
    print()

def get_firebase_web_api_key():
    print("📋 Step 1: Firebase Web API Key")
    print("-" * 40)
    print("1. Go to https://console.firebase.google.com/")
    print("2. Select your project")
    print("3. Go to Project Settings (⚙️ icon)")
    print("4. In 'General' tab, find 'Web API Key'")
    print("5. Copy the key (starts with 'AIzaSy...')")
    print()
    
    api_key = input("Enter your Firebase Web API Key: ").strip()
    
    if not api_key.startswith('AIzaSy'):
        print("⚠️  Warning: API key should start with 'AIzaSy'")
        confirm = input("Continue anyway? (y/n): ").lower()
        if confirm != 'y':
            return get_firebase_web_api_key()
    
    return api_key

def get_firebase_service_account():
    print("\n📋 Step 2: Firebase Service Account")
    print("-" * 40)
    print("1. Go to Project Settings → Service accounts")
    print("2. Click 'Generate new private key'")
    print("3. Download the JSON file")
    print("4. Open the JSON file and copy its contents")
    print()
    
    print("Options:")
    print("1. Paste JSON content directly")
    print("2. Provide path to JSON file")
    
    choice = input("Choose option (1/2): ").strip()
    
    if choice == "1":
        print("\nPaste the JSON content (press Enter twice when done):")
        lines = []
        while True:
            line = input()
            if line == "" and lines and lines[-1] == "":
                break
            lines.append(line)
        
        json_content = "\n".join(lines[:-1])  # Remove last empty line
        
    elif choice == "2":
        file_path = input("Enter path to JSON file: ").strip()
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                json_content = f.read()
        except FileNotFoundError:
            print("❌ File not found!")
            return get_firebase_service_account()
        except Exception as e:
            print(f"❌ Error reading file: {e}")
            return get_firebase_service_account()
    else:
        print("❌ Invalid choice!")
        return get_firebase_service_account()
    
    # Validate JSON
    try:
        json.loads(json_content)
        return json_content
    except json.JSONDecodeError:
        print("❌ Invalid JSON format!")
        return get_firebase_service_account()

def set_environment_variables(api_key, service_account):
    print("\n🔧 Setting Environment Variables...")
    print("-" * 40)
    
    # Set environment variables
    os.environ['FIREBASE_WEB_API_KEY'] = api_key
    os.environ['FIREBASE_SERVICE_ACCOUNT_KEY'] = service_account
    
    print("✅ Environment variables set successfully!")
    print()
    print("Current session variables:")
    print(f"FIREBASE_WEB_API_KEY: {api_key[:20]}...")
    print(f"FIREBASE_SERVICE_ACCOUNT_KEY: {len(service_account)} characters")

def create_env_file(api_key, service_account):
    print("\n📝 Creating .env file...")
    
    env_content = f"""# Firebase Configuration
# Generated by setup_env.py

FIREBASE_WEB_API_KEY={api_key}
FIREBASE_SERVICE_ACCOUNT_KEY={json.dumps(service_account)}
"""
    
    try:
        with open('.env', 'w', encoding='utf-8') as f:
            f.write(env_content)
        print("✅ .env file created successfully!")
        print("💡 You can use this file with python-dotenv library")
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")

def test_configuration():
    print("\n🧪 Testing Configuration...")
    print("-" * 40)
    
    try:
        # Test Firebase API Key
        from lib.firebase import API_KEY
        if API_KEY:
            print("✅ Firebase API Key loaded successfully")
        else:
            print("❌ Firebase API Key not loaded")
            return False
    except Exception as e:
        print(f"❌ Error loading Firebase API Key: {e}")
        return False
    
    try:
        # Test Service Account
        import json
        service_account = os.environ.get('FIREBASE_SERVICE_ACCOUNT_KEY', '')
        if service_account:
            json.loads(service_account)
            print("✅ Firebase Service Account JSON is valid")
        else:
            print("❌ Firebase Service Account not set")
            return False
    except Exception as e:
        print(f"❌ Error validating Service Account: {e}")
        return False
    
    return True

def print_next_steps():
    print("\n🎉 Setup Complete!")
    print("=" * 60)
    print("Next steps:")
    print("1. Start the server:")
    print("   cd Server")
    print("   python server.py")
    print()
    print("2. Start the client (in another terminal):")
    print("   cd Client")
    print("   python run.py")
    print()
    print("3. Create an account and start chatting!")
    print()
    print("💡 Note: Environment variables are set for this session only.")
    print("   To make them permanent, add them to your shell profile.")

def main():
    print_banner()
    
    try:
        # Get Firebase credentials
        api_key = get_firebase_web_api_key()
        service_account = get_firebase_service_account()
        
        # Set environment variables
        set_environment_variables(api_key, service_account)
        
        # Create .env file
        create_env_file(api_key, service_account)
        
        # Test configuration
        if test_configuration():
            print_next_steps()
        else:
            print("\n❌ Configuration test failed!")
            print("Please check your Firebase credentials and try again.")
            sys.exit(1)
            
    except KeyboardInterrupt:
        print("\n\n👋 Setup cancelled by user.")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
